
language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

before_script:
- vendor/bin/phpunit install --dev

script:
  - phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov

php:
  - '7.0'
  - '7.1'
  - '7.2'

